# Use the official Node.js image as base
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json /app/

# Install dependencies
RUN npm install

# Copy the rest of the frontend code to the container
COPY . .

# Set the environment variable for API base URL
ARG FASTAPI_APP_API_BASE_URL
ENV FASTAPI_APP_API_BASE_URL=${FASTAPI_APP_API_BASE_URL}

# Build the React app
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Start the React app
CMD ["npm", "start"]
